### ISSUE TITLE
I want to train the DProQA from scratch

### ISSUE THREAD

**Issue by onlyonewater** [jianlin-cheng/DProQA#2]
could release the train code? I want to train the DProQA from scratch. Thanks!!!

**Comment by XiaoChen1992** [comment]
Sorry to reply to you late. We released all training details in our paper, and you can find the all parameters' settings here at https://github.com/jianlin-cheng/DProQA/blob/main/configs/Lab_saw_mulitase_gate_af2_decoy_knn10_seed2222.json.  

Best
