### ISSUE TITLE
Double sigmoid

### ISSUE THREAD

**Issue by pgniewko** [jianlin-cheng/DProQA#3]
In this [line](https://github.com/jianlin-cheng/DProQA/blob/f24e9119155142b34af4c40c78d71ae37c7019b8/src/graph_transformer_edge_layer.py#L52), `torch.mul(edges.data[attention_score], torch.sigmoid(edges.data[gate]))`, you call `torch.sigmoid` on `edges.data[gate]`, for `gate=e_gate`. But `e_gate` is calculated in this [line](https://github.com/jianlin-cheng/DProQA/blob/f24e9119155142b34af4c40c78d71ae37c7019b8/src/graph_transformer_edge_layer.py#L119) as:
```
g.edata['e_gate'] = torch.sigmoid(e_gate.view(-1, self.num_heads, self.out_dim))
```

So you execute `torch.sigmoid` twice, whereas you intended to call it only once, like you did [here](https://github.com/jianlin-cheng/DProQA/blob/f24e9119155142b34af4c40c78d71ae37c7019b8/src/graph_transformer_edge_layer.py#L100C20-L100C20). 

Isn't this a bug ?

**Comment by XiaoChen1992** [comment]
Hi, 

Thank you for pointing out this issue. It is a bug. However, so far, we do not have recourse to retrain the model. You still can use this model for inference, all our paper's results and CASP15 results were generated by this model.  But if you want to train your own data with DProQA, you need to modify the code to remove the additional sigmoid function. 

Best,
